### ISSUE TITLE
Slow opening of notebooks on binder

### ISSUE THREAD

**Issue by suryadheeshjith** [m2lines/data-gallery#34]
Opening any of the notebooks on binder seems to be taking a lot more time than expected. I do not know if this is an issue only on my side. 

Also found a bug in the binder link in this notebook - https://m2lines.github.io/data-gallery/notebooks/pycnocline_depth_mom6.html (link - https://mybinder.org/v2/gh/m2lines/data-gallery/main?labpath=src%2Fnotebooks%pycnocline_depth_mom6.ipynb. I believe it should be changed to https://mybinder.org/v2/gh/m2lines/data-gallery/main?labpath=src%2Fnotebooks%2Fpycnocline_depth_mom6.ipynb)

**Comment by jbusecke** [comment]
Can you add a description of this issue?

**Comment by suryadheeshjith** [comment]
Testing this with again, it looks like it was an issue on my side. Closing this for now.
