### ISSUE TITLE
Add website preview as part of the CI?

### ISSUE THREAD

**Issue by jbusecke** [m2lines/data-gallery#4]
Hey everyone, 
I think it would be great to be able to preview changes as they would appear on the [final website](https://m2lines.github.io/data-gallery/) as part of the CI. This would be in addition to the review via review NB. The former will enable us to see if things are nicely converted to html the latter will let us focus on the content of the notebooks.

Having both would be awesome. 

I have implemented something similar in out [LEAP-Pangeo Technical Documentation](https://github.com/leap-stc/leap-stc.github.io/tree/main/.github/workflows) which you might be able to use as a template. I am happy to help/discuss this further. 

I think in terms of priority this is a medium for me, as it it not crucial to move ahead, but I think it will be very useful to avoid issues with the website (I have added labels to group by priority).

**Comment by adcroft** [comment]
A web preview would be very helpful and avoid broken pages. If this is not a heavy lift to implement then I think this should be done earlier rather later to help smooth PR evaluation.

**Comment by IamShubhamGupto** [comment]
@adcroft im working on this feature for the week, it'll be out soon

**Comment by IamShubhamGupto** [comment]
@jbusecke I can't seem to get GitHub actions to leave a comment, maybe you can help me fix that, im adding you as a developer now
